// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxhwtylesmtgwlytstwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4aHd0eWxlc210Z3dseXRzdHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDgzMTMsImV4cCI6MjA2NTU4NDMxM30.RsHNz4Tk6D5yO4XR9BQQd6okLHdnFPXo0oPz7d6UI08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);